services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - neo4j_storage:/data
      - ./import:/import
    environment:
      - NEO4J_AUTH=neo4j/infraconnexion
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    ports:
      - "8474:7474"
      - "7474:7474"
      - "7687:7687"
      - "8687:7687"
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: DevOnlyPass
    command: server --console-address ":9001" /data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 5
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - portainer_storage:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
volumes:
  neo4j_storage:
  minio_storage:
  portainer_storage:
